import { IonContent, IonPage } from '@ionic/react';
import './Terms.scss';

import { ReactComponent as Back } from "../../assets/arrowleft.svg";
const PaymentTerms: React.FC = () => {
  return (
    <IonPage>
      <IonContent fullscreen>
          <div className='pamentTermsWrap'>
              <div className='privacyHeader'>
                  <Back />
                  <h2> Payment Terms </h2>
              </div>
              <div className='privacyContent'>
                  <h2> Chainj's Privacy Policy </h2>
                  <p> Last updated: February 20, 2023 </p>
                  <p> Hello from Chainj.io </p>
                  <p> The terms listed below (these "Payment Terms") apply to any payments you send or receive through Chainj.io's website, www.Chainj.io (the "Site") (584 Easy Street, Midland, ON, L4R 4C2l). </p>
                  <p> Card payments from the U.S. are processed by Chainj.io (584 Easy Street, Midland, ON, L4R 4C2), while international card payments are processed by Chainj Incubator (Suite 9, Sendall Court, Winstanley Estate, Wandsworth, London, SW11 2HE). Chainj, Chainj.io, and Chainj Incubator are collectively referred to as "Chainj," "we," or "us" in this document. </p>
                  <p> Before sending or receiving payments over the Site, please carefully read these Payment Conditions. You acknowledge and agree to be bound and comply with these Payment Conditions by sending or receiving payments through the Site on your own behalf, or on behalf of your employer or another business (where applicable). The Chainj General Terms of Service and Chainj Business Terms of Service, as applicable (collectively, the "Terms of Service"), are supplemented by these Terms. </p>
                  <h3> Key Terms </h3>
                  <p> Words that are capitalized but not otherwise defined above shall have the meanings ascribed to them in the Terms of Service </p>
                  <p> Your Chainj Balance is the total of your Volunteer Income, Mentor Returned Payments from Canceled Orders, and/or Chainj Business Balance (as defined in the Chainj Business Terms of Service). </p>
                  <p> The Payment Services Provider(s) are companies that offer payment services to Mentors and Volunteers in connection with the Chainj platform. These services include collecting money from Mentors for purchases, sending and withdrawing money to Volunteers, exchanging currencies for payments and withdrawals in local currencies, and holding money in connection with Chainj Balances. </p>
                  <p> Income is the money that Volunteers get from successfully completed orders and may, subject to these Conditions, either withdraw or spend to make purchases on Chainj. </p>
                  <h2> Receiving Payment </h2>
                  <h3> General </h3>
                  <p> A certain number of Chainj crypto-time-coins equivalent to the amount of hours and minutes you volunteered will be minted and credited to your account for each Mission you offer and successfully complete. </p>
                  <p> After an order is finished, Chainj approves Volunteers. For a definition of "finished order," see the "Orders" section of the Terms of Service. </p>
                  <p> The money spent for an order will be restored to the Mentor's Chainj Balance if it is cancelled (for whatever reason). </p>
                  <p> In accordance with the laws of their country, volunteers are responsible for paying any direct or indirect taxes, such as GST, VAT, or income taxes, that may be applicable to them based on their residency, location, or other factors. Volunteers certify and guarantee that they abide by and always will abide by their legal obligations to pay taxes in accordance with local laws. All applicable taxes and fees that may be imposed on the Volunteers are already included in the price that is displayed on the Mission page or the Logo Creator order page. </p>
                  <h3> Appointment as Limited Payment Collection Agent: </h3>
                  <p> Volunteer hereby appoints Chainj as Volunteer's limited authorized Platform with the sole authority to co-mine (through its Platform Services) with Mentor, hold, and remit such crypto-time-currency incentives to Volunteer. Volunteer acknowledges that any payment made by Mentor through the Chainj Platform Vault shall be regarded as equivalent to payment made directly to Volunteer. When the reward is received in the Chainj Platform Vault (or its Platform Services, as applicable), Mentor's reward obligation to the Volunteer will be satisfied. Chainj is in charge of sending the money to the Volunteer's Vault in accordance with these Payment Conditions. The Volunteer will only have recourse against Chainj and not the Mentor directly if Chainj (through Platform Services) fails to pay any such sums to the Volunteer. Volunteer consents to Chainj using any terms of service, receipts, disclosures, or notifications, including but not limited to receipts given to Mentors, that Chainj may determine appropriate or necessary to describe or otherwise reflect the terms included herein. </p>
                  <p> For the purposes of enabling the creation of Chainj crypto-time-currency between Volunteers and Mentors, delivering such rewards to Volunteers, and holding Chainj balances in Volunteer's Vaults, Chainj serves as the Platform Service Provider. </p>
                  <p> Stripe, Chainj's payment service provider, handles all fiat payments made by Mentors to the Chainj Marketplace for Chainj Subscription Services on the Chainj platform. The Payment Service Provider for Chainj handles all currency exchange services related to such payments as well. </p>
                  <h3> Withdrawing Rewards </h3>
                  <p> You must have created at least one Chainj Vault in your dashboard for the withdrawal of monies to a Crypto Wallet of your choice before you can withdraw your rewards. Your Chainj Vault will be the exclusive repository for all digital incentives that are withdrawable. The Platform Service Provider for Chainj will offer all payment services, including withdrawal services. </p>
                  <p> There can only be one vault per Chainj profile. </p>
                  <p> Following a 14-day safety clearance window starting from the time the order is marked as complete, rewards are only made available for withdrawal through the Revenue page. Following a seven-day period of safety clearance following the marking of the order as complete, Top Rated Volunteers are qualified to withdraw incentives. The length of the safety clearance period for Chainj Studio Members is determined by the level status or classification of the Studio Lead (Level 1, Top Rated, Pro, etc.). </p>
                  <p> Using the use of your external crypto wallet in conjunction with Chainj's vault, volunteers can withdraw their rewards. Regarding award conditions, check the Withdrawal Section below. You must click on the selected vault to start the withdrawal process in order to withdraw your available funds. </p>
                  <p> Chainj may temporarily block a Volunteer's ability to withdraw rewards due to security concerns in order to stop fraudulent or illegal activities. This can be the result of security problems or bad behaviour that other users have reported. Only the amount that is currently in your account may be withdrawn. </p>
                  <p> Fees for cashing out awards are 1% of the points received. </p>
                  <p> Withdrawals are irreversible and final. Once this procedure starts, there is no turning back. </p>
                  <p> Volunteers occasionally have the option to withdraw Prizes into several wallets. The local currency amount of your Chainj Balance may change daily in accordance with exchange rate movements and may also contain conversion fees since your Chainj Balance is always calculated from its US$ value. The choice to withdraw any available Prizes is always available to volunteers. </p>
                  <p> Prizes is always available to volunteers. </p>
                  <p> Following thorough ownership verification of the account in issue, 90 days from the date of the last cleared payment received in their account, and with Chainj's approval, volunteers will be able to take their rewards from disabled accounts. </p>
                  <h2> PURCHASING </h2>
                  <h3> General </h3>
                  <p className='outline'> Mentors use the Order Now button on the Volunteer's Mission page or Custom Offer to generate orders and pay their monthly Chainj Subscription fees for the services of Chainj time-tracking Volunteers (Incorporate these features throughout the Legal descriptions). For the purpose of collecting all Subscription payments from Mentors and/or returning overpayments or refunds, Chainj collaborates with Payment Services Providers. Moreover, Chainj holds money related to Volunteers' Chainj Balances. Chainj's payment service providers, Stripe, handle all payment services related to the collection of funds on the Chainj Platform. </p>
                  <p> In order to accept and store awards from Mentor (through its Platform Services) and send such payments to Volunteer, Chainj acts as the limited authorized crypto storage agent for Volunteer. Mentor's payment obligation to Volunteer will be satisfied after Chainj (or its Payment Services Provider, as applicable) receives payment. Chainj is in charge of sending the monies to the Volunteer in accordance with these Payment Terms through its Payment Service Provider. The Volunteer will only have recourse against Chainj and not the Mentor directly if Chainj (via Payment Services Provider) fails to pay any such sums to the Volunteer. </p>
                  <p> Most places accept credit cards, PayPal, chainj credits, existing chainj balances, or chainj credits for making purchases on chainj.com. In some places, additional payment options can be required. You can find more details about the payment options here. </p>
                  <p> At the moment of purchase, service costs are applied, and you can examine and accept the total amount required to be paid. They pay for administrative costs. The service charges are 5.5% of the purchase price as of March 2021. An additional US$2 small order fee will be charged for purchases under US$50. </p>
                  <p> The next purchase you make will immediately be deducted from your current Chainj Balance. </p>
                  <p> You are not permitted to request money from Volunteers or to make payments in any other way than through the Chainj.com website. If you were instructed to use a different payment method, please report it right away to customer support by clicking here. </p>
                  <p> You consent to receiving invoices and/or payment receipts from Chainj by email, the Site, or electronic PDF documents. </p>
                  <p> Services Providers in order to combat fraud, unlawful transactions (such money laundering), disputes, or other obligations. Payment service providers may additionally gather whatever other data they deem essential for processing withdrawal payments. The payment information submitted to Payment Service Providers is not disclosed to Chainj, and this information is subject to the Payment Service Provider's privacy policy. To learn more, please visit our privacy statement. </p>
                  <p> By using any payment method and/or providing payment details for purchases on Chainj, you represent and warrant that (a) you are legally able to provide such information; (b) you are legally able to use the payment method(s); (c) if you are an employee or agent of a company or person that owns the payment method, you are authorized to use the payment method to make purchases on Chainj by that company or person; and (d) you are at least 18 years old. </p>
                  <p> using Chainj Logo Creator to make purchases </p>
                  <p> All logo designs have a set price in US dollars and can be ordered as part of the basic logo package or other packages as listed on the order page for logo designs. </p>
                  <p> You can examine a watermarked version of the logo design that is integrated with your brand name before completing a purchase, and you can use the editing tools to make additional changes to the logo design. Orders placed with Logo Designs cannot be cancelled once money has been received. </p>
                  <p> In addition to the Logo Design you select, you may buy a package that enables you to use the editing feature of the Logo Maker to produce one or more modifications of the Logo Design. When you purchase a package that includes access to the editing tool for the Logo Maker, we provide you a compensable, non-exclusive, non-transferable, non-sublicensable, and personalized right to use the editing tool to modify the Logo Design you selected. Please be aware that redistributing the Logo Design and/or variants is prohibited and may subject your account to restrictions. Chainj maintains the right, in its sole discretion, to discontinue the service or to offer you widely accessible upgrades to the editing tool. The Volunteer who designed the logo also offers redesign services for sale. The Volunteer sets the cost of such redesign services, and a service fee will only be applied to the additional redesign services. Please see the "Disputes and Cancellations" section below for further information regarding the cancellation of logo redesign services. </p>
                  <h3> Local Currencies </h3>
                  <p> On Chainj, you can make payments in a variety of currencies. The closest whole number will be used to round all costs for your convenience. You will be able to see the exact amount due when you check out. You will be billed in the currency shown on the payment page, unless otherwise specified. All currency exchange services in connection with payments in local currencies are performed by Chainj's Payment Services Provider. Nonetheless, there are some circumstances in which you will be charged in US dollars even when the price is presented in a different currency because specific payment systems do not accept particular currencies. In any case, before you finalize the payment, you will receive a clear disclosure of the actual charged amount (in the actual payment currency). </p>
                  <p> Due to the fact that all Chainj pricing are calculated from their original US$ price, non-US$ currency prices may vary daily based on changes in exchange rates and may additionally contain conversion costs. Mentors can always change their currency to pay in US dollars. </p>
                  <p> The amount restored to your Chainj Balance would depend on the exchange rate in effect on the day your Order was cancelled if you paid for it in a currency other than US dollars. The amount that is returned may therefore differ from the amount that was paid in local currency while always preserving the same US$ value. </p>
                  <p> Even if it is represented in a currency other than US dollars, your Chainj fiat balance is always valued in US dollars. Therefore, should you choose to view your Chainj fiat Balance in any currency other than US$, it may change daily in accordance with exchange rate fluctuations, while always maintaining the same US$ value. Users always have the option to view their Chainj fiat Balance in US$ by changing their selected displayed currency. </p>
                  <h3> Chainj Credits </h3>
                  <p> In certain instances, Chainj may offer you credits (“Chainj Credits” or “Credits”), either for promotional purposes or otherwise, to be used for purchasing Missions and/or other services offered on the Site. Your available Credit balance will appear in your account. Your valid Chainj Credits will be automatically applied to your next purchase and can be viewed in your order summary after you place the order. Unless stated otherwise, Chainj Credits expire following three months from their receipt. Chainj Credits serve only as an incentive to use Chainj, and, therefore, are not redeemable for cash, have no cash value and are nonrefundable. Once used, Chainj Credits may not be returned to your account even if your Order gets canceled. Chainj Credits may be subject to additional conditions and restrictions as will be disclosed to You upon receipt of the Credits. Credits may be voided in the event of fraud, misuse, or violation of these Terms. Chainj reserves the right to modify or cancel the Chainj Credits program at any time. If you or Chainj deactivate or suspend your Chainj account, any unused Chainj Credits in your account will be forfeited. </p>
                  <h3> Promo Codes </h3>
                  <p> From time to time we may offer you promo codes for purchasing Missions and/or other services offered on the Site, on special discounts. Promo Codes are valid only for purchases on Chainj and are subject to different time limitations and will expire after their predefined term. To exercise your promo code, simply enter the code on the checkout page. If you fail to do so, your purchase will not be eligible for the discount. Promo codes are limited to one use per user and may not be used or combined with any other promotion. For orders that are composed of one or more milestones, the promo code will apply to the first milestone only. Promo Codes do not apply to Chainj Rewards. Promo codes may be subject to additional conditions and restrictions as will be disclosed to you upon receipt of the promo codes. Promo codes may be voided in the event of fraud, misuse, or violation of the Terms of Service. Chainj reserves the right to modify or cancel promo codes at any time. </p>
                  <h3> Taxes </h3>
                  <p> Chainj may be required by applicable laws to charge Mentors with indirect taxes (such as Sales Tax, VAT or GST) or to withhold taxes. Any amount Chainj will be required to collect will be in addition to the Subscription purchase amount and any other fees payable by the Mentor, as required by applicable laws. </p>
                  <p> Indirect taxes are in addition to the price shown on the site, and in any event, any such taxes will always be displayed to the Mentor before payment. </p>
                  <p> Users are responsible for paying any direct or indirect taxes, including any GST, VAT, or income tax, which may apply to them depending on residency, location or otherwise, under provisions of their jurisdiction. </p>
                  <h3> Disputes and Cancellations  </h3>
                  <p> We encourage our Mentors and Volunteers to try and settle conflicts amongst themselves. If for any reason this fails after using the Resolution Center or if you encounter non-permitted usage on the Site, users can contact Chainj's Customer Support department for assistance at support@chainj.io </p>
                  <h3> Basics </h3>
                  <p> Order cancellations can be performed on Chainj, when eligible, by Customer Support or through the Resolution Center per order. In the event that you encounter an issue related to the service provided in an order, you are encouraged to use the Site's dispute resolution tools to attempt to resolve the matter. </p>
                  <p> Mentors filing a Subscription dispute or reversing a payment through your payment provider or your bank is a violation of these Payment Terms. Doing so may get your account temporarily or permanently disabled. Note: Once you have filed a dispute with your payment provider, the funds will be ineligible for a refund due to our obligations towards the payment provider. </p>
                  <p> Chainj, through its Payment Services Provider, reserves the right to cancel Subscription orders or place funds on hold for any suspected fraudulent transactions made on the Site. </p>
                  <p> All transfer and assignment of intellectual property from Volunteer to the Mentor shall be subject to agreed rewards and the payment may be canceled if delivery is not completed for any reason. </p>
                  <p> If an Mission is canceled (for any reason), the rewards paid will be returned to the Chainj Pool. </p>
                  <p> Revisions to deliveries can be performed by Volunteers based on the Volunteer’s Mission and customer care. Volunteers may determine the amount of revisions they wish to offer, including no revisions. </p>
                  <p> Requests for revisions can be performed through the Order Page while the order is marked as Delivered. </p>
                  <p> Requesting to gain more services from Volunteers beyond the agreed requirements by using the Request Revisions button is not allowed. </p>
                  <h3> Order Cancellations  </h3>
                  <p> Chainj encourages Mentors and Volunteers to resolve service disputes mutually using the Resolution Center. </p>
                  <p> Eligibility for requests to Chainj to cancel an order will be assessed by our Customer Support team based on a number of factors, including violations of our Terms of Service and/or our Community Standards, general misconduct, and improper usage of the Chainj delivery system. See below for Order specific eligibility. </p>
                  <p> Completed orders (or, where applicable, completed milestones) may be canceled, upon review of our Customer Support team, up to 14 days after the order (or Milestone) is marked as complete. Please be advised that orders cannot be partially canceled (i.e. we can only cancel the entire order when it is justified). </p>
                  <p> In rare circumstances where we find it appropriate, our Customer Support team may cancel a completed order even after 14 days have passed from its completion. In such cases, the rewards paid for the canceled order will be returned to the Chainj Pool and will be deducted from the Volunteer’s Chainj Balance or, if there are no sufficient amounts in the Volunteer’s Chainj Balance, from future rewards of such Volunteer. </p>
                  <p> Orders are not eligible to be canceled based on the quality of service/materials delivered by the Volunteer if the service was rendered as described in the Mission Page. You may rate your experience with the Volunteer on the Order Page, including the overall level of service quality received. </p>
                  <p> You must use Chainj Resolution Center (resolutioncentre@chainj.io )to address your concerns and desired resolution related to the service provided by their Volunteer prior to contacting Customer Support. Customer Support will not take any action against Orders where the applicable has failed to inform their Volunteer of issues related to the Volunteer’s service and will allow Volunteers to provide a resolution first. This does not include non-permitted usage of Chainj. </p>
                  <p> Any non-permitted usage of Chainj encountered during a Mission, after being reviewed by our Customer Support team, may result in the Mission being canceled. This includes, but not limited to; harassment, unlawful behavior, or other violations of Chainj’s Terms of Service. </p>
                  <p className='bulletsTop'> Chainj Customer Support will cancel Missions based on, but not limited to, the following reasons: </p>
                  <p className='bullets'> Active orders (after requirements were submitted to the Volunteer and before the Volunteer delivers on Chainj): </p>
                  <p className='bullets'> The Volunteer is late and unresponsive for more than 24 hours while the order is marked as Late. </p>
                  <p className='bullets'> Users are abusive towards the other party through threats of low ratings or leveraging order materials (such as logins, personal information) against each other. </p>
                  <p className='bullets'> Users supplied or included copyright/trademark infringing materials as part of their requirements or the Volunteer’s delivery. </p>
                  <p className='bullets'> The user is no longer an active Chainj user due to Terms of Service violations or closure of their account. </p>
                  <p className='bullets'> Delivered Orders (after the Volunteer clicks Deliver Now and before the order is marked as complete) </p>
                  <p className='bullets'> The Volunteer uses the Delivery system to extend the delivery due date to complete the requested service without providing the final delivered service. Note: Multiple reported offenses will result in permanent suspension of your account. </p>
                  <p className='bullets'> The Volunteer delivers no files and/or proof of work related to the agreed upon order requirements. Note: Subjectivity of the materials in question will be reviewed by our Customer Support team. </p>
                  <p className='bullets'> The Volunteer requests additional payments, on or off the Chainj platform, by withholding the final delivery of services directly related to the agreed requirements. </p>
                  <p className='bullets'> The Volunteer is withholding the final delivery of services for improved ratings. </p>
                  <p className='bullets'> Users who abuse the Request Revisions button to gain more services from Volunteers beyond the agreed requirements. </p>
                  <p className='bullets'> Users who threaten to leave a damaging review to gain more services from the Volunteer not related to the agreed requirements. </p>
                  <p className='bullets'> Completed Orders (after the order is marked as complete and before the 14-day limitation) </p>
                  <p className='bullets'> Users who have been reported to use copyright/trademark infringing materials after verification and with proof. </p>
                  <p className='bullets'> Users who did not purchase commercial use rights and are reported to have used the materials commercially. Note: Terms of Commercial use are found on the Volunteer’s Mission Page and cannot be retroactively included once the order is completed for over 14 days. </p>
                  <p> Chainj Customer Support will review cases of Order delivery manipulation that prevents users from fully utilizing our Resolution Center that enabled the order to be marked as complete. </p>
                  <h3> Chargebacks </h3>
                  <p> Chainj reviews cases of payment provider chargebacks and disputes on behalf of Mentors. Although results vary per case due to each chargeback reason, we work hard on resolving disputes in the Mentor’s favor. If the chargeback case allows, Chainj (or Chainj’s Payment Services Provider) will return parts or full revenue back to Mentors, otherwise the chargeback amount will be borne by the Mentor. </p>
                  <h3> Refunds </h3>
                  <p> Chainj does not automatically refund payments made for canceled Subscriptions back to your payment provider. Funds from Mission cancellations are either NOT minted or they are returned to the Chainj Pool and are available for future co-minting on the Chainj Platform. If the service fees were not returned to your Chainj fiat Balance following an Subscription cancelation, such fees’ amount will be exempted from your next month’s Subscriptikno purchase on Chainj. </p>
                  <p> Deposit refunds (i.e. refunds directly to your payment provider) can be performed by our Customer Support team, based on the Subscriber’s original payment amount and currency. To prevent fraud and abuse, we limit the total amount of times users can request a payment provider refund, which is subject to review by our Customer Support team. Such refunds may be subject to an additional fee. </p>
                  <h2> General Terms </h2>
                  <h3> Modifications </h3>
                  <p> Chainj may make changes to these Payment Terms from time to time. When these changes are made, Chainj will make a new copy of the terms available on this page. </p>
                  <p> You understand and agree that if you use Chainj after the date on which the Payment Terms have changed, Chainj will treat your use as acceptance of the updated Payment Terms. </p>
                  <h3> Disclaimer of Warranties </h3>
                  <p> YOUR USE OF THE SITE, ITS CONTENT AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE IS AT YOUR OWN RISK. THE SITE, ITS CONTENT AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER CHAINJ NOR ANY PERSON ASSOCIATED WITH CHAINJ MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY OR AVAILABILITY OF THE SITE. </p>
                  <p> THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. </p>
                  <h3> Limitation on Liability </h3>
                  <p> IN NO EVENT WILL CHAINJ, ITS AFFILIATES OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SITE, ANY WEBSITES LINKED TO IT, ANY CONTENT ON THE WEBSITE OR SUCH OTHER WEBSITES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SITE OR SUCH OTHER WEBSITES, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE. </p>
                  <p> IN ACCEPTING LIABILITY AS THE LIMITED AUTHORIZED PAYMENT PLATFORM OF VOLUNTEER, CHAINJ AND ITS AFFILIATES ASSUME NO LIABILITY FOR ANY ACTS OR OMISSIONS OF VOLUNTEER. </p>
                  <p> THE FOREGOING DOES NOT AFFECT ANY LIABILITY WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW. </p>
              </div>
          </div>
      </IonContent>
    </IonPage>
  );
};

export default PaymentTerms;
