import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar } from '@ionic/react';
import './Privacy.scss';

import { ReactComponent as Back } from "../../assets/arrowleft.svg";
const Privacy: React.FC = () => {
  return (
    <IonPage>
      <IonContent fullscreen>
          <div className='privacyPolicyWrap'>
              <div className='privacyHeader'>
                  <Back />
                  <h2> Privacy Policy </h2>
              </div>
              <div className='privacyContent'>
                  <h2> THE CHAINJ PRIVACY POLICY  </h2>
                  <p> Please carefully read this privacy statement to understand how Chainj Incubator, 584 Easy Street, Midland, ON, L4R 4C2 ("Chainj," "we") uses personal information (the "Policy").  Before using www.Chainj.io, the Chainj mobile app, any other pertinent websites, applications, services, or products, or any other Chainj-operated website that links to this policy, you acknowledge that you have read and understand this Policy (each, the "Site"). There may be periodic changes to this policy. In addition to posting any changes we make to this policy on this website, we will also, to the extent permitted by applicable law, take any other necessary steps, such as notifying you of substantial changes. Changes to this Policy become effective as of the date that it was "Last Modified," if one is given. We suggest you to constantly check the Policy for updates and changes. </p>
                  <h3> THE SHORT VERSION </h3>
                  <p> Information We Collect - Most of the information we collect is provided by you directly when you register to use the site, complete forms, or enroll in one of our programs. Furthermore, we keep track of any comments you leave on our blogs or forums, as well as your communications with other Chainj users and interactions with Chainj itself. Additionally, we automatically collect information about you as you access, browse, read, or otherwise use the Site. Information is also obtained from other sources, including open sources and independent providers. </p>
                  <p> Our Legal Basis for Processing Your Personal Data - Whenever permitted by relevant law, any processing of your personal data shall be backed by a "lawful ground" for processing, as indicated below. </p>
                  <h3> THE SHORT VERSION </h3>
                  <p> How Will We Use the Data Gathered? </p>
                  <p> We use your personal information to manage the Site, analyze user behaviour on the Site, and carry out our agreements with you. In compliance with applicable laws and regulations, we also use it to advertise the Site, our services, and the Chainj marketplace. We also use it to preserve the integrity and security of the market, stop fraud, get in touch with you and send you direct marketing messages. </p>
                  <p> How Long Do We Keep Personal Information - We only keep personal information as long as it's required to accomplish the aforementioned goals. Nonetheless, there are times when we keep personal information for longer periods of time. </p>
                  <p> Children: Access to this website is restricted to individuals who are at least 18 years old and of legal age to form legally binding contracts. Minors under the age of 18 and at least 13 years old may only use accounts held by parents or legal guardians with the proper consent. Minors under the age of 13 are not permitted to use the Site or Chainj services. We do not intentionally gather personal information about children under 13 years old. </p>
                  <p> Sharing Personal Information with Other Parties - We share personal information with third parties in order to run the Site, provide you with our services, carry out our legal and regulatory obligations, and prevent fraud, violations, and criminal activities. </p>
                  <p> Where We Store Personal Information: Some of the personal data you provide to us may be maintained or processed on our behalf by third-party suppliers and data processors, who may be headquartered in nations like Canada or Europe. </p>
                  <h3> Cookies </h3>
                  <p> We use cookies and associated technologies to improve and personalize your experience, provide our services, assess the efficacy of our websites, and run marketing initiatives (such as web beacons, pixels, tags, and scripts). </p>
                  <p> Do Not Track (DNT) - Our website ignores signals sent by the Do Not Track (DNT) protocol. </p>
                  <p> External Links: The Site might offer access to external links to third-party websites. Chainj is not in charge of how any personal data you may have submitted to a third-party website is used if you decide to leave the Site and go there. </p>
                  <p> Security - To maintain the security of the Site and your personal information and to prevent unauthorized access, loss, misuse, alteration, destruction, or damage to it, we use industry-standard technologies and internal processes. </p>
                  <p> User Rights in the EU, EEA, and the UK - Where we process personal data related to EU, EEA, and UK users, extra rules apply to our processing with regard to your data subject rights under EU data protection regulations. These additional rules are explained below. </p>
                  <p> Specific Requirements for California Residents: If you reside in California, you are entitled to the following privacy protections. </p>
                  <h3> Updating Personal Information  </h3>
                  <p> We take precautions to ensure that the Personal Information we collect is accurate and up-to-date, and we provide you with the ability to update your Personal Information through your account profile settings. If you believe your information is inaccurate or incorrect in any other way, kindly let us know as soon as possible. </p>
                  <p> Contact Us - To exercise your rights regarding your personal information, please email privacy@Chainj.com or submit a Customer Relations ticket. If you utilize Chainj ServiceArea, send an email to ServiceArea-Support@Chainj.io. In the longer version of the Policy, your rights are covered in more detail. </p>
                  <p> Just a handful of the highlights are listed below. To learn more about the information we receive, how we use it, what cookies are, and other issues, we encourage you to read the longer version of our Policy, which is provided below. </p>
                  <p> The official assertion Mentors, volunteers, and other site visitors (hence, "users"), as well as partners, influencers, and other collaborators working with Chainj, are committed to respecting the privacy of their personal information. This commitment includes Chainj and all of its associated businesses, such as Chain and Chainj Incubator. We believe you have a right to know how we handle the information we gather about you by using the Site or when you come to see us. This Policy describes the privacy requirements that apply to the Site, the services provided by Chainj, as well as affiliates, influencers, and other collaborators who are persons. By accessing and/or using the Site and its associated websites, applications, services, and goods, and/or by registering for an account and/or taking part in our affiliate, influencer, or similar program, you agree that you have read and understand how we collect, use, disclose, process, and retain your personal information in accordance with this Policy. The guidelines for limiting information sharing are included in this policy. </p>
                  <p> Information We Compile the Information You Provide. When you sign up for the Site, use it, fill out forms, answer surveys or take skills tests, use the Site as a collaborator, and/or sign up for an affiliate, influencer, or similar program, we ask for some personal information from you. A valid email address, username, and login details for your Facebook or Google account are included in this information. In addition, we may ask for or otherwise collect information from you, including your name, profile details, billing information, physical address, phone number, and other contact information, transactional data, payment information (for instance, in some cases, we process your payment method and credit card number), taxpayer information and forms, information about other social networks linked accounts, information about your listed gigs, purchases, education, a list of your qualifications, and so on. Additionally, we preserve a record of all communications you have with Chainj, as well as any posts you make on our blogs or forums and any communications you have with other Chainj users. </p>
                  <h3> Information We Acquire Automatically </h3>
                  <p> We may collect data about you while you access, browse, view, or otherwise use the Site. In other words, whenever you enter the Site, we automatically collect personal information about your usage of the Site, including searches you conduct, the pages you visit, and other actions you take on the Site, like transactions and communications with other users. Additionally, we collect, use, and process data about such usage, including your IP address, geolocation, device and connection information, browser information, web-log information, and the URLs of the websites you visited or interacted with before or after using the Site. We also collect and use information about how cookies and other similar technologies are used, as will be further discussed below. We use this information to provide our services to you, enhance user experience, tailor your browsing, and monitor the Site to prevent fraud and objectionable content or behaviour. </p>
                  <p> In order to improve your online experience at Chainj, we have also introduced impression reporting. While you view our advertisements, we log your Global Unique Identifier (GUID), HTTP request data such user agent, IP address, host, and URL as well as the country or continent the request was made from. We also log information about your browser and your device's operating system and version. </p>
                  <h3> Data gathered from external sources. </h3>
                  <p> We also obtain information from third party vendors and/or other commercially available sources in accordance with applicable laws, such as: </p>
                  <p className='bullets'> Third party vendors that give us data to supplement the knowledge we already have about you. For instance, service providers may send us fraud warnings as part of our efforts to stop fraud and analyze the risk. We also obtain information from enrichment service providers to improve and tailor your experience as well as to manage and assess our campaigns. </p>
                  <p className='bullets'> We may get information from a third-party service (like Google, Facebook, or LinkedIn) if you link, connect, or login to your account with that service. This information could include specifics about your registration and profile. Depending on your preferences and the privacy settings of that service, this information can change and is controlled by that service. </p>
                  <p className='bullets'> If you want to invite contacts from your G-suite directory, we will be able to read their contact information, subject to your G-suite permission. We'll provide you the ability to invite people to your Chainj account using this information. Also, we will use anonymized, aggregated data for internal purposes. </p>
                  <p className='bullets'> If you integrate information from third parties into your account or otherwise link your account with third party systems, tools, or products, we will obtain certain information about you from those third parties with your permission. </p>
                  <p className='bullets'> We may also obtain information about you if you are invited to Chainj by another user (for example, as part of our collaboration tools and referral program). Only a little amount of information about you, such as your email address or other contact details, may be given to us in this situation, but we will still use it for the intended purpose and in accordance with this Privacy Policy. </p>
                  <p> We combine your personal information with information we automatically collect or purchase from other companies for the purposes described in this Policy. </p>
                  <h3> Why We Use Your Personal Information </h3>
                  <p> Whenever permitted by applicable laws, any processing of your personal information must be justified by a "lawful ground" for processing. Most of the time, processing will be justified on the grounds that: </p>
                  <p className='bullets'> you have authorized us to use your personal information for a specific purpose </p>
                  <p className='bullets'> our use of your personal information is necessary to carry out a contract or to take other actions to enter into a contract with you (for example, to provide you with the services you have purchased); </p>
                  <p className='bullets'> the processing is necessary to comply with a relevant legal requirement or regulatory requirement that we have (for example, to provide you with the services you have purchased). </p>
                  <h3> What Are We Going To Do With The Info Gathered? </h3>
                  <p> Your personal information will be used by us in the following ways: to operate the Site, to carry out our obligations under our contract with you, to create and improve our services, and to provide you with high-quality support and security. For instance, we use personal data to verify your identity. In addition, we use your information to set up and maintain your account, validate or reissue passwords, record activity, enable member interactions, provide customer support, and occasionally contact you. The information we collect helps us develop and improve our services, comprehend and assess both our own performance and your preferences, as well as adjust and customize our products to better fit your needs (including by making Mission suggestions, ranking search results, etc.). </p>
                  <p className='bullets'> to safeguard market integrity, keep services and markets safe and secure, and stop fraud. We may use personal information, for example, to carry out security checks and risk evaluations, keep an eye on the accuracy of content, detect and stop fraud and other improper behaviour, enforce our terms of service, and comply with legal obligations. To achieve the aforementioned objectives, we employ some behavioural analytics. On rare occasions, automatic processes may limit or restrict your use of Chainj if we detect activity that we believe poses a risk to the Chainj marketplace, other users, our community, or third parties. If you want to challenge any such choice, please  </p>
                  <p className='bullets'> to contact you at your request, on another occasion that you authorized, or in any other way permitted by this Policy. </p>
                  <p className='bullets'> to promote and advertise the Site, our services, and the Chainj marketplace. We use the information we have about you, for example, to send direct marketing messages (as set forth below), to show content we believe will be of interest to you, to plan and conduct referral programs, contests, and other promotional events, to maintain accurate records of business dealings, to respond to reasonable requests from public authorities, to comply with applicable laws and regulations, and to take other actions as may be necessary. </p>
                  <p> We will ask for your consent before using your information for any purpose other than those listed in this Policy. </p>
                  <h3> Direct sales  </h3>
                  <p> We use your personal information to get in touch with you about Chainj specials, services, or goods that may be of interest to you. </p>
                  <p> Your consent, our legitimate interest, or another legal justification may be used to process your personal information for marketing purposes. This can be done by phone calls, SMS, emails, postal mail, targeted online ads, and SMS. Any form of direct marketing is subject to your right to object at any time. To do this, either send an email to optout@Chainj.com or click the opt-out link found in each correspondence.  </p>
                  <p> We take measures to keep the quantity of direct marketing to a reasonable and appropriate level based on the information we have about you. Also, we give you information that we believe may be useful or interesting to you. </p>
                  <h3> How long do we keep personal information? </h3>
                  <p> We adhere to the general rule of only keeping personal information as long as it takes to accomplish the objectives for which it was collected. Nonetheless, there are some circumstances where we might keep your personal data for a longer period of time. For the purposes of enforcing our Site conditions, complying with relevant laws, preventing fraud, collecting any fees due, resolving disputes, troubleshooting issues, assisting with investigations, and taking other steps as mentioned below, we shall store personal information from closed accounts. For the following reasons, we shall keep personal information on file: </p>
                  <p className='bullets'> as long as it is required and pertinent for our business operations, such as keeping a complete record of your interactions with us in case of disputes or complaints; </p>
                  <p className='bullets'> in regard to personal information from open accounts. </p>
                  <p> Children Access to this website is restricted to individuals who are at least 18 years old and legally able to engage into binding contracts. Minors under the age of 18 and at least 13 years old may only use accounts held by parents or legal guardians with the proper consent. Minors under the age of 13 are not permitted to use the Site or Chainj services. We do not intentionally gather personal information about children under 13 years old. Parents and guardians must always be aware of their children's whereabouts. When we learn that we have acquired or gathered personal data from a child under the age of 13, we will delete that data. If you believe we may have any information from or about a child under the age of 13, please send an email to privacy@Chainj.com. </p>
                  <p> sharing confidential information with third parties </p>
                  <p> We never rent or sell your personal information to a third party for marketing purposes without your explicit consent. </p>
                  <p className='bullets'> With other users and website visitors. The users of the Site will be able to view your username, country, and other details about your actions once you register. The images you upload, your public portfolio, information about your gigs, ratings, and any other information you might choose to add in your profile are all included in this data. Also, we provide you the choice to publicly post on blogs, forums, and other ad hoc platforms. Please be aware that when you use such services, some information, including your user name and profile, together with the content you upload, will be made public. Your information might also be shared with other users when you message them or engage with them in other ways. When you share your data with other Chainj users or post information about yourself, you do so at your own risk. Users will function as independent controllers of your personal information if you choose to disclose it with them, such as Sellers who provide you with a service through Chainj. You must make sure that other users meet your standards because Chainj cannot ensure that all users will keep the confidentiality of the information shared with them. The confidentiality of the information provided with Sellers is a requirement of Chainj's Terms of Service. </p>
                  <p> -law-...., and thes-.., and the-. We trade personal information with service providers who partner with us under a contract in order to run the Site, create and administer your account, and offer ancillary services and solutions. Hosting services, billing and payment processors, payment vendors, CRM systems, forum hosting, community management services, data and cybersecurity services, web analytics and performance tools, translation tools, IT SaaS services, session recording, communication systems, mailing systems, data optimization and marketing services, data enrichment services, legal and financial advisors, or technical consultants are a few examples of these. We take the appropriate organizational and technical measures to ensure that third parties adequately protect your personal information and only use it as instructed by us, in line with the applicable legal requirements; </p>
                  <p className='bullets'> </p>
                  <p> For a legal reason. When responding to a subpoena or court order, judicial process, or regulatory authorities, we may share personal information with law enforcement agencies, public authorities, or other parties if we believe doing so is required by law or that doing so is reasonably necessary to comply with legal processes; when we believe it is necessary or appropriate to disclose personal information to law enforcement authorities, such as to investigate actual or suspected fraud; We share personal information with payment processors, fraud detection organizations, and other similar third parties in order to enable payments made through the Site, safeguard the Site and protect it from fraud, unauthorized transactions (including money laundering), claims, or other liabilities. Our social media partners also receive personal data from us. Our website offers many social media solutions, such as single sign-on tools. We also share a small amount of personal information with social media networks and marketing partners like Facebook and Google in order to promote our services or the Chainj marketplace. These features and third-party services may collect information about you and set cookies in order to operate. These third parties' policies affect the functionalities that they offer. </p>
                  <p className='bullets'> With those you communicate with. We exchange private data to aid in facilitating user interactions. To ensure the services you receive from the Seller will meet your needs, for instance, if you are a Mentor, we may share limited information about you with the Seller (such as the fact that this is your first purchase on Chainj); this limited information sharing is only done to enhance the services offered by the Seller and your user experience. </p>
                  <p className='bullets'> With our business partners. In order to operate the Site, provide our services to you, and for the other purposes indicated here, we share personal information with Chainj's corporate affiliates (Chainj, Chainj Incubator), who are related by common control; and </p>
                  <p> The Google Privacy Policy and Terms of Service are applicable with regard to the data gathered by reCAPTCHA, which is another kind of protection for this website. It is necessary to employ Google reCAPTCHA to stop fraud and automated machines from abusing the website. Please see Google's privacy statement for more information.</p>
                  <h3> Exactly where We Keep Your Personal Data </h3>
                  <p> Some of the personal data you give us may be held or processed on our behalf by third-party suppliers and data processors who may be based in countries with legal systems that are different from your own, such Canada and the UK. There are transfers of personal data from the European Economic Area ("EEA") to nations outside the EEA that are not judged to have an appropriate degree of data protection from a European perspective, such as the United States, whether to third parties or internally. We offer adequate protections for data transfers to these recipients outside the EEA, including by entering into European Union (EU) standard contractual clauses, as revised from time to time, and/or comparable data transfer protections. We shall take all reasonable measures required to ensure the security and adherence to this Policy of the handling of your personal information. </p>
                  <h3> Cookies </h3>
                  <p> We use cookies and related technologies (such web beacons, pixels, tags, and scripts) to make your experience better and more personalized, to deliver our services, to assess the effectiveness of our website, and for marketing. Please go to our Cookie Policy to learn more about how we and our third party service providers use cookies and how you can manage these cookies. </p>
                  <p> Do Not Track Do Not Track (DNT) is a privacy setting that users can enable in some web browsers, allowing users to opt out of tracking by websites and online services. Although our Cookie Policy explains how you can choose not to receive cookies, we do not respect browser requests to not be tracked online (also known as "Do Not Track" requests). </p>
                  <h3> Outside Links </h3>
                  <p> Please be aware that the Site contains links to third-party websites, and that if you leave the Site to visit one of these websites, Chainj has no control over how those websites use the information you submit about yourself and is not responsible for how they use it. Every website you visit should have a privacy policy that you can review. Only the personal data gathered by our Site is covered by this Policy. Even if you publish on an official Chainj page on the social network, if you submit content, including personal information, and then tag the Site, your input will be subject to that social network's terms of use and privacy policy. These terms of use and privacy policies are not under our control, and we have not evaluated how effective they are. Hence, before providing any personal information, you should study these. </p>
                  <h3> Security  </h3>
                  <p> We employ industry-standard technologies and internal policies to safeguard the security of the Site, our services, and personal information and to prevent unauthorized access, loss, misuse, alteration, destruction, or damage to it. We periodically maintain a PCI DSS (Payment Card Industry Data Security Standards) certification (with regard to credit card payment), as necessary, among other things. Additionally, we contractually guarantee that any third party processing your personal information does so in a manner that ensures the confidentiality, integrity, and security of your data. Although we will try our best to safeguard your personal information, we cannot guarantee the security of any data provided to the Site as data transfer over the internet is not totally secure. Once we get your data, we will endeavour to prevent unwanted access by following tight protocols and utilizing security features. Users who register on the site commit to keeping their passwords strictly confidential and not sharing them with anyone. On request, we can give you further details regarding our data security procedures. </p>
                  <h3> Users' Rights in the EU, EEA, and the UK </h3>
                  <p> If you reside in the EU, the EEA, or the UK, this portion of the Policy applies to you. Chainj, located at 584 Easy Street, Midland, Ontario, L4R 4C2, is the Controller (as defined by the EU and UK General Data Protection Regulation, or "GDPR") for the processing of personal data. </p>
                  <p> You have the following rights regarding your personal information under applicable EU regulation:  </p>
                  <p className='bullets'> to obtain information about how and on what basis your personal information is processed and to obtain a copy; </p>
                  <p className='bullets'> to correct inaccurate personal information; </p>
                  <p className='bullets'> to erase your personal information in certain circumstances, such as when (a) you believe that we no longer need to hold your personal information; (b) we are processing your personal information on the basis that I you have given us your consent to do so. </p>
                  <p> In certain situations, you may have the right to object to how we are processing your personal data on grounds specific to your situation, in which case we may be compelled to stop. Moreover, if your personal data is processed for direct marketing purposes, you have the right to object at any time to the processing of personal data concerning you for such marketing, which includes profiling to the extent that it is related to such direct marketing. In this scenario, we will no longer process your personal information for these purposes. </p>
                  <p> You also have the option to file a complaint with a supervisory authority for data protection in addition to the aforementioned rights. Please note that the right of access and the right to erasure do not constitute absolute rights and the interests of other individuals may restrict your right of access or erase in accordance with local laws. </p>
                  <p> We will ask you for additional data to confirm your identity and for security purposes, before disclosing data requested by you. We reserve the right to charge a fee where permitted by law. We will decline to process requests that jeopardize the privacy of others, are extremely impractical, or would cause us to take any action that is not permissible under applicable laws. Additionally, as permitted by applicable laws, we will retain where necessary certain personal information for a limited period of time for record-keeping, accounting and fraud prevention purposes. </p>
                  <h3> Updating Personal Information </h3>
                  <p> We take steps to ensure that the personal information we collect is accurate and up to date, and we provide you with the opportunity to update your information through your account profile settings. In the event that you believe your information is in any way incorrect or inaccurate, please let us know immediately. We will make sure we investigate the matter and correct any inaccuracies as quickly as possible where necessary or give you ways to update it quickly or to delete it - unless we have to keep that information for legitimate business or legal purposes. When updating your personal information, we will ask you to verify your identity before we can act on your request. If for any reason you have a problem with deleting your personal information, please contact Chainj's Customer Support and we will make reasonable efforts to delete any such information pursuant to any applicable privacy laws. </p>
                  <p> You can review and change your personal information by logging into the Site and visiting your account profile page. </p>
                  <p> If you delete your User Generated Content (“UGC”), as defined in the Chainj Terms of Service, from the Site, copies of your UGC may remain viewable in cached and archived pages, or might have been copied or stored by other Site users. Proper access and use of information provided on the Site, including UGC, is governed by our Terms of Service. </p>
                  <h3> Contact Us </h3>
                  <p> To exercise any of your rights in connection with your personal information, we kindly ask that you open a Customer Relations ticket. Please include all the relevant details, so your ticket can be handled correctly. We will process any requests in line with any local laws and our policies and procedures. You may also contact us at privacy@Chainj.io. </p>
                  <p> If you have any questions (or comments) concerning this Policy, please email our team at privacy@Chainj.io, and we will make an effort to reply within a reasonable timeframe. For Chainj ServiceArea users, please contact us at ServiceArea-Support@Chainj.io. For the purposes of GDPR (Article 27), you may contact our EU representative under the following contact details: Chainj Incubator, Suite 9, Sendall Court, Winstanley Estate, Wandsworth, London, SW11 2HE. </p>
              </div>
          </div>
      </IonContent>
    </IonPage>
  );
};

export default Privacy;
